DefaultVolume = 24

[Clients]
64e83383e1e40000 = { name = "38" }
64e833845cd00000 = { name = "39" }
64e833857f040000 = { name = "40" }

[Files]
"internet cricket" = { folder = 1, file = 1, duration = 10.032000 }

[FileSets]
"internet cricket" = { regex = "internet cricket" }

[Effects."basic sound test"]
Algorithm             = "loop"
Duration              = { Mean = 30000 }
FileSets.main         = "internet cricket"
Lease.MaxClients      = 1
Lease.MinClients      = 1
Lease.Type            = "sound"
Lease.FleetFraction   = { Mean = 0.5, Variance = 0.2, Distribution = "uniform" }
Parameters.fileDelay  = { Mean = 0 }
Parameters.fileReps   = { Mean = 1,  Variance = 0, Distribution = "normal" }
Parameters.groupDelay = { Mean = 15, Variance = 0, Distribution = "normal" }

[Effects.unison]
Algorithm             = "unison"
Duration              = { Mean = 30 }
Lease.MinClients      = 1
Lease.Type            = "light"
Lease.FleetFraction   = { Mean = 1.0 }
Lease.MaxWait         = { Mean = 30 }
Parameters.blinkSpeed = { Mean = 2.0, Variance = 0.1, Distribution = "normal" }
Parameters.blinkDelay = { Mean = 0.1, Variance = 0.05,Distribution = "uniform" }
Parameters.blinkReps  = { Mean = 4,   Variance = 1,   Distribution = "normal" }
Parameters.groupDelay = { Mean = 8,   Variance = 3,   Distribution = "uniform" }
Parameters.groupReps  = { Mean = 4,   Variance = 3,   Distribution = "normal" }

[Players.light]
Delay        = { Mean = 10, Variance = 10, Distribution = "uniform" }
StartupDelay = { Mean = 0 }
Weights      = { unison = 1 }

[Players.sound]
Delay        = { Mean = 10, Variance = 10, Distribution = "uniform" }
Weights      = { "basic sound test" = 1 }
